version: '3.7'
# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ../:/var/www/sites:ro
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  # PHP Service
  php:
    build: config/php
    working_dir: /var/www/sites
    volumes:
      - ../:/var/www/sites
    command: vendor/bin/phpunit tests





